apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: dev
  namespace: {{ .Release.Namespace }}
spec:
  addresses:
    - {{ .Values.metallb.IPAddressPool | quote }}
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: empty
