name: Test UDS Capability

on:
  pull_request:
    paths-ignore:
      - "**.md"
      - "docs/**"
      - "CODEOWNERS"

permissions:
  id-token: write
  contents: read

jobs:
  test-clean-install:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Zarf
        uses: defenseunicorns/setup-zarf@main
        with:
          # renovate: datasource=github-tags depName=defenseunicorns/zarf versioning=semver
          version: v0.31.2

      - run: "curl -s https://raw.githubusercontent.com/k3d-io/k3d/main/install.sh | bash"
        shell: bash

      - name: Create Zarf Package
        run: zarf package create --confirm

      - name: Deploy the capability
        run: zarf package deploy zarf-package-uds-k3d-multi-*.tar.zst --confirm
