name: Test UDS Capability

on:
  pull_request:
    paths-ignore:
      - "**.md"
      - "docs/**"
      - "CODEOWNERS"

permissions:
  id-token: write
  contents: read

jobs:
  test-clean-install:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup UDS
        if: always()
        uses: defenseunicorns/uds-common/.github/actions/setup@v0.2.2

      - name: Create and deploy the uds-k3d package
        run: uds run

      - name: Validate uds-k3d package
        run: uds run validate

