name: Publish k3s image

on:
  push:
    branches:
      - main
    paths:
      - docker/**
      - .github/workflows/publish-image.yaml

jobs:
  publish-k3s-image:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: ["v1.27.11-k3s1", "v1.28.7-k3s1", "v1.29.2-k3s1"]

    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4

      - uses: docker/setup-buildx-action@d70bba72b1f3fd22344832f00baa16ece964efeb # v3.3.0

      - name: Setup UDS
        if: always()
        uses: defenseunicorns/uds-common/.github/actions/setup@859a9b2469c8a6c24c414fe34b127ec5677aea62 # v0.4.3
        with:
          username: ${{secrets.IRON_BANK_ROBOT_USERNAME}}
          password: ${{secrets.IRON_BANK_ROBOT_PASSWORD}}

      - name: Login to GHCR
        uses: docker/login-action@e92390c5fb421da1463c202d546fed0ec5c39f20 # v3
        with:
          registry: ghcr.io
          username: dummy
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish the custom k3s image
        run: uds run publish-image --set VERSION=${{matrix.version}}
