name: Publish k3s image

# Workflow is not currently being used, switched to a manual trigger only
on: workflow_dispatch
  # push:
  #   branches:
  #     - main
  #   paths:
  #     - docker/**
  #     - .github/workflows/publish-image.yaml

jobs:
  publish-k3s-image:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: ["v1.2.3-k3s1"] # Placeholder

    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - uses: docker/setup-buildx-action@b5ca514318bd6ebac0fb2aedd5d36ec1b5c232a2 # v3.10.0

      - name: Install UDS CLI
        uses: defenseunicorns/setup-uds@ab842abcad1f7a3305c2538e3dd1950d0daacfa5 # v1.0.1
        with:
          # renovate: datasource=github-tags depName=defenseunicorns/uds-cli versioning=semver
          version: v0.22.0

      - name: Environment setup
        run: |
            uds run actions:setup-environment \
            --set REGISTRY1_USERNAME="${{ secrets.IRON_BANK_ROBOT_USERNAME }}" \
            --set REGISTRY1_PASSWORD="${{ secrets.IRON_BANK_ROBOT_PASSWORD }}" \
            --set GH_TOKEN="${{ secrets.GITHUB_TOKEN }}" \
            --set CHAINGUARD_IDENTITY="${{ secrets.CHAINGUARD_IDENTITY }}"
        shell: bash

      - name: Publish the custom k3s image
        run: uds run publish-image --set VERSION=${{matrix.version}} --no-progress
