name: Publish k3s image

on:
  push:
    branches:
      - main
    paths:
      - docker/**

jobs:
  publish-k3s-image:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - name: Setup UDS
        if: always()
        uses: defenseunicorns/uds-common/.github/actions/setup@v0.3.6
        with:
          username: ${{secrets.IRON_BANK_ROBOT_USERNAME}}
          password: ${{secrets.IRON_BANK_ROBOT_PASSWORD}}

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: dummy
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish the custom k3s image
        run: uds run publish-image
