name: Publish k3s image

on:
  push:
    branches:
      - main
    paths:
      - docker/**
      - .github/workflows/publish-image.yaml

jobs:
  publish-k3s-image:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: ["v1.27.13-k3s1", "v1.28.9-k3s1", "v1.29.4-k3s1"]

    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f # v4

      - uses: docker/setup-buildx-action@2b51285047da1547ffb1b2203d8be4c0af6b1f20 # v3.2.0

      - name: Setup UDS
        if: always()
        uses: defenseunicorns/uds-common/.github/actions/setup@05f42bb3117b66ebef8c72ae050b34bce19385f5 # v0.3.6
        with:
          username: ${{secrets.IRON_BANK_ROBOT_USERNAME}}
          password: ${{secrets.IRON_BANK_ROBOT_PASSWORD}}

      - name: Login to GHCR
        uses: docker/login-action@e92390c5fb421da1463c202d546fed0ec5c39f20 # v3
        with:
          registry: ghcr.io
          username: dummy
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish the custom k3s image
        run: uds run publish-image --set VERSION=${{matrix.version}} --no-progress
