name: Publish k3s image

# Workflow is not currently being used, switched to a manual trigger only
on: workflow_dispatch
  # push:
  #   branches:
  #     - main
  #   paths:
  #     - docker/**
  #     - .github/workflows/publish-image.yaml

jobs:
  publish-k3s-image:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: ["v1.28.11-k3s2", "v1.29.6-k3s2", "v1.30.2-k3s2"]

    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4

      - uses: docker/setup-buildx-action@4fd812986e6c8c2a69e18311145f9371337f27d4 # v3.4.0

      - name: Setup UDS
        if: always()
        uses: defenseunicorns/uds-common/.github/actions/setup@172a905901cb9bd76d096d2850bf31af5c5a4fa1 # v0.8.0
        with:
          username: ${{secrets.IRON_BANK_ROBOT_USERNAME}}
          password: ${{secrets.IRON_BANK_ROBOT_PASSWORD}}

      - name: Login to GHCR
        uses: docker/login-action@0d4c9c5ea7693da7b068278f7b52bda2a190a446 # v3
        with:
          registry: ghcr.io
          username: dummy
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish the custom k3s image
        run: uds run publish-image --set VERSION=${{matrix.version}} --no-progress
