# Copyright 2026 Defense Unicorns
# SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Defense-Unicorns-Commercial

name: Publish k3s image

on:
  push:
    branches:
      - main
    paths:
      - docker/**
      - .github/workflows/publish-image.yaml
  workflow_dispatch:

jobs:
  publish-k3s-image:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # renovate: datasource=docker depName=rancher/k3s versioning=semver
        version: ["v1.35.8-k3s1"]

    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - uses: docker/setup-qemu-action@1f40c72289eff860ee54a304f1438e3cff362e0a # v4.3.0

      - uses: docker/setup-buildx-action@37fe631027851001ddb9b187196cc803df7f5f0e # v4.3.0

      - name: Login to GHCR
        uses: docker/login-action@dbcb813823bdd20940b903addbd779551569679f # v4.6.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Install UDS CLI
        uses: defenseunicorns/setup-uds@d6add59d4c2ca789ed7c92741e91bd340b4e950b # v1.0.2
        with:
          # renovate: datasource=github-tags depName=defenseunicorns/uds-cli versioning=semver
          version: v0.36.0

      - name: Environment setup
        run: |
            echo "MARU_AUTH=\"{\"raw.githubusercontent.com\": \"${{ secrets.GITHUB_TOKEN }}\"}\"" >> "$GITHUB_ENV"
            uds run actions:setup-environment \
            --set GH_TOKEN="${{ secrets.GITHUB_TOKEN }}"
        shell: bash

      - name: Publish the custom k3s image
        run: uds run publish-image --set VERSION=${{matrix.version}} --no-progress
